name: Delete old folders from github pages

on:
  schedule:
    - cron: "0 23 * * 1,3,5"
  workflow_dispatch:

jobs:
  delete-old-folders:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Delete old folders
        run: python ./scripts/delete-old-folders.py --n-days 14 --folder-name playwright-report

      - name: Commit all changed files back to the repository
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: gh-pages
          commit_message: Delete folders older than 14 days
